# Generated by Django 3.1.5 on 2021-01-25 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('close_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='WashPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wash.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('car_washes', models.ManyToManyField(related_name='wash_types', through='wash.WashPrice', to='wash.CarWash')),
            ],
        ),
        migrations.AddField(
            model_name='washprice',
            name='wash_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wash.washtype'),
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('wash_speed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wash.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garages', to='wash.carwash')),
            ],
        ),
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_wash', to='wash.location'),
        ),
    ]
