# Generated by Django 3.1.5 on 2021-01-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='title',
            field=models.CharField(default='Isani', max_length=255),
            preserve_default=False,
        ),
    ]
